/**
 * Demo dataset loader – reads from /demo-data/ directory.
 * Used when the app is in demo mode (no valid LICENSE_KEY).
 * All data is read-only; no writes to GitHub in demo mode.
 */

import type { Answer, Evidence, Mapping, Questionnaire } from './types';
export { DEMO_LIMITS } from './types';

// In demo mode we serve static JSON so it works in edge/serverless contexts.
// The actual YAML files are in /demo-data/ for GitHub storage reference.

export const DEMO_ANSWERS: Answer[] = [
  {
    id: 'ans-001',
    title: 'Encryption at Rest',
    intent_keywords: ['encryption', 'at rest', 'AES', 'storage', 'disk encryption', 'data protection'],
    short_answer: 'All customer data is encrypted at rest using AES-256-GCM with AWS-managed or customer-managed keys.',
    tags: ['encryption', 'data-protection', 'infrastructure'],
    frameworks: ['SOC2', 'ISO27001', 'CAIQ', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-06-01',
    evidence_ids: ['ev-001', 'ev-002'],
    long_answer_md: `## Encryption at Rest\n\nAll customer data stored in our systems is encrypted at rest using AES-256-GCM.\n\n### Database\nAmazon RDS instances use AES-256 encryption enabled at volume level.\n\n### Object Storage\nS3 buckets use SSE-S3 (AES-256) by default. CMKs via KMS available for Enterprise customers.\n\n### Backups\nAll automated backups are encrypted using the same key as the source data.`,
  },
  {
    id: 'ans-002',
    title: 'Encryption in Transit',
    intent_keywords: ['TLS', 'HTTPS', 'transit', 'in-flight', 'transport security', 'SSL', 'network encryption'],
    short_answer: 'All data in transit is protected by TLS 1.2 or higher. TLS 1.0 and 1.1 are disabled.',
    tags: ['encryption', 'network', 'tls'],
    frameworks: ['SOC2', 'ISO27001', 'CAIQ'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-06-01',
    evidence_ids: ['ev-002'],
    long_answer_md: `## Encryption in Transit\n\nAll communications between clients and our services use TLS 1.2+.\n\n- TLS 1.0 and 1.1 are disabled on all endpoints\n- Perfect Forward Secrecy (PFS) is supported via ECDHE\n- HSTS headers enforce HTTPS on all web properties\n- Internal service-to-service communication is also encrypted via mTLS`,
  },
  {
    id: 'ans-003',
    title: 'Multi-Factor Authentication',
    intent_keywords: ['MFA', 'two-factor', '2FA', 'multi-factor', 'authentication', 'TOTP', 'phishing-resistant'],
    short_answer: 'MFA is enforced for all internal employee access. Customers can enable MFA via their account settings; MFA is required for admin roles.',
    tags: ['authentication', 'access-control', 'identity'],
    frameworks: ['SOC2', 'ISO27001', 'SIG', 'CAIQ'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-05-15',
    evidence_ids: ['ev-003'],
    long_answer_md: `## Multi-Factor Authentication\n\n### Employees\nAll CloudWidget employees are required to use MFA for access to company systems. We use TOTP-based authenticator apps and hardware security keys (FIDO2/WebAuthn) for privileged users.\n\n### Customers\nMFA is available to all customers and required for admin-level accounts. Supported methods: TOTP, SMS (legacy), and WebAuthn.`,
  },
  {
    id: 'ans-004',
    title: 'Role-Based Access Control (RBAC)',
    intent_keywords: ['RBAC', 'role-based', 'access control', 'least privilege', 'permissions', 'authorization'],
    short_answer: 'Access to systems and customer data is governed by role-based access control (RBAC) following the principle of least privilege.',
    tags: ['access-control', 'authorization', 'identity'],
    frameworks: ['SOC2', 'ISO27001', 'CAIQ', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-05-15',
    evidence_ids: ['ev-003'],
    long_answer_md: `## Role-Based Access Control\n\nAccess is granted based on job function using predefined roles.\n\n- **Viewer**: Read-only access to assigned projects\n- **Editor**: Create/modify resources within assigned projects\n- **Admin**: Full control within an organization\n- **Super Admin**: Platform-level; restricted to <5 internal staff\n\nAll role assignments are reviewed quarterly via our access review process.`,
  },
  {
    id: 'ans-005',
    title: 'Incident Response Plan',
    intent_keywords: ['incident response', 'IRP', 'breach', 'security event', 'incident management', 'CSIRT'],
    short_answer: 'We maintain a documented Incident Response Plan (IRP) tested annually. Security incidents are tracked, escalated, and reported within SLA windows.',
    tags: ['incident-response', 'governance', 'operations'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-01-10',
    evidence_ids: ['ev-004'],
    long_answer_md: `## Incident Response\n\nOur Incident Response Plan (IRP) follows the NIST SP 800-61 framework:\n\n1. **Preparation** – CSIRT established, runbooks maintained\n2. **Detection & Analysis** – SIEM alerts, anomaly detection\n3. **Containment** – Automated isolations + manual escalation\n4. **Eradication & Recovery** – Root cause analysis, patching\n5. **Post-Incident Review** – Written RCA within 5 business days\n\n### Notification SLAs\n- Customer notification: within 72 hours of confirmed breach\n- Regulatory notification: per applicable law (GDPR 72h, etc.)`,
  },
  {
    id: 'ans-006',
    title: 'Vulnerability Management',
    intent_keywords: ['vulnerability', 'CVE', 'patching', 'scanning', 'penetration test', 'SAST', 'DAST'],
    short_answer: 'We conduct automated vulnerability scanning continuously and perform annual penetration tests by a third-party assessor. Critical patches are applied within 24 hours.',
    tags: ['vulnerability-management', 'patching', 'security-testing'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-03-01',
    evidence_ids: ['ev-005', 'ev-006'],
    long_answer_md: `## Vulnerability Management\n\n### Scanning\n- **SAST**: Integrated into CI/CD pipeline (every pull request)\n- **DAST**: Weekly automated scans against staging environment\n- **Container scanning**: Every image build scanned for CVEs\n- **Infrastructure**: Continuous scanning via AWS Inspector + Nessus\n\n### Patching SLAs\n| Severity | SLA |\n|----------|-----|\n| Critical | 24 hours |\n| High | 7 days |\n| Medium | 30 days |\n| Low | 90 days |`,
  },
  {
    id: 'ans-007',
    title: 'Data Backup and Recovery',
    intent_keywords: ['backup', 'recovery', 'RTO', 'RPO', 'disaster recovery', 'restore', 'BCP'],
    short_answer: 'Customer data is backed up daily with 30-day retention. RPO is 1 hour; RTO is 4 hours. Backups are encrypted and stored in a separate AWS region.',
    tags: ['backup', 'disaster-recovery', 'availability'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'infrastructure@cloudwidget.example',
    last_reviewed: '2025-04-01',
    evidence_ids: ['ev-007'],
    long_answer_md: `## Data Backup and Recovery\n\n### Backup Schedule\n- **Continuous**: Point-in-time recovery for databases (15-minute intervals)\n- **Daily**: Full snapshot of all volumes\n- **Weekly**: Exported to cross-region S3 bucket\n\n### Recovery Objectives\n- **RPO (Recovery Point Objective)**: 1 hour\n- **RTO (Recovery Time Objective)**: 4 hours\n\n### Testing\nBackup restoration is tested quarterly; results documented and reviewed.`,
  },
  {
    id: 'ans-008',
    title: 'Security Awareness Training',
    intent_keywords: ['security training', 'awareness', 'phishing simulation', 'employee training', 'security culture'],
    short_answer: 'All employees complete mandatory security awareness training annually. Phishing simulations are conducted quarterly.',
    tags: ['training', 'people-security', 'governance'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'hr@cloudwidget.example',
    last_reviewed: '2025-02-01',
    evidence_ids: ['ev-008'],
    long_answer_md: `## Security Awareness Training\n\nAll employees must complete security awareness training within 30 days of hire and annually thereafter.\n\n### Topics Covered\n- Phishing and social engineering recognition\n- Password hygiene and password manager usage\n- Data handling and classification\n- Incident reporting procedures\n- Secure remote work practices\n\n### Phishing Simulations\nWe run quarterly phishing simulations. Employees who click are automatically enrolled in refresher training.`,
  },
  {
    id: 'ans-009',
    title: 'Third-Party Vendor Risk Management',
    intent_keywords: ['vendor', 'third-party', 'supplier', 'sub-processor', 'vendor risk', 'due diligence', 'TPRM'],
    short_answer: 'We maintain a vendor risk management program. Critical sub-processors are reviewed annually; new vendors undergo security assessment before onboarding.',
    tags: ['vendor-risk', 'supply-chain', 'governance'],
    frameworks: ['SOC2', 'ISO27001', 'SIG', 'CAIQ'],
    owner: 'procurement@cloudwidget.example',
    last_reviewed: '2025-01-15',
    evidence_ids: ['ev-003'],
    long_answer_md: `## Third-Party Vendor Risk Management\n\n### Assessment Process\n1. Security questionnaire for all vendors handling customer data\n2. Review of SOC 2 / ISO 27001 certifications\n3. Contractual DPA and security requirements\n4. Annual re-assessment for critical vendors\n\n### Sub-Processors\nA current list of sub-processors is available at: https://cloudwidget.example/legal/subprocessors`,
  },
  {
    id: 'ans-010',
    title: 'Data Retention and Deletion',
    intent_keywords: ['data retention', 'deletion', 'right to erasure', 'purge', 'data lifecycle', 'GDPR', 'privacy'],
    short_answer: 'Customer data is retained for the duration of the contract plus 90 days. Deletion is permanent and verifiable upon request. GDPR right-to-erasure requests are honoured within 30 days.',
    tags: ['data-privacy', 'gdpr', 'retention'],
    frameworks: ['SOC2', 'ISO27001', 'CAIQ', 'SIG'],
    owner: 'privacy@cloudwidget.example',
    last_reviewed: '2025-03-15',
    evidence_ids: ['ev-009'],
    long_answer_md: `## Data Retention and Deletion\n\n### Retention Periods\n- Active customer data: Duration of contract\n- Post-termination grace period: 90 days\n- Audit logs: 12 months (regulatory requirement)\n- Backups: 30 days rolling\n\n### Deletion\nUpon request or after the retention period:\n1. Data purged from primary database\n2. Backups containing the data expire within 30 days\n3. Certificate of deletion available upon request`,
  },
  {
    id: 'ans-011',
    title: 'Business Continuity Planning',
    intent_keywords: ['BCP', 'business continuity', 'disaster recovery', 'continuity plan', 'resilience'],
    short_answer: 'We maintain a Business Continuity Plan (BCP) tested annually. Our platform is designed for 99.9% uptime with multi-region failover.',
    tags: ['business-continuity', 'resilience', 'availability'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'operations@cloudwidget.example',
    last_reviewed: '2025-01-10',
    evidence_ids: ['ev-007'],
    long_answer_md: `## Business Continuity Planning\n\nOur BCP covers critical business functions and IT systems. Key elements:\n\n- **Multi-region deployment**: Active-passive across 2 AWS regions\n- **Automated failover**: DNS failover within 5 minutes\n- **Annual BCP test**: Tabletop exercise + partial failover drill\n- **Vendor continuity**: Critical vendor alternatives identified\n\n### SLA Commitments\n| Tier | Uptime SLA |\n|------|------------|\n| Standard | 99.9% |\n| Enterprise | 99.99% |`,
  },
  {
    id: 'ans-012',
    title: 'Penetration Testing',
    intent_keywords: ['penetration testing', 'pentest', 'red team', 'external assessment', 'ethical hacking'],
    short_answer: 'Annual penetration tests are conducted by an independent third-party assessor. Results and remediation timelines are available under NDA.',
    tags: ['security-testing', 'assessment', 'compliance'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-03-01',
    evidence_ids: ['ev-005'],
    long_answer_md: `## Penetration Testing\n\nWe engage an independent security firm to conduct annual penetration tests.\n\n### Scope\n- External network and web application\n- Internal network (limited scope)\n- API security\n- Mobile applications (if applicable)\n\n### Results\nHigh/critical findings are remediated before the report is finalised. A summary letter and executive report are available under NDA on request.`,
  },
  {
    id: 'ans-013',
    title: 'Logging and Monitoring',
    intent_keywords: ['logging', 'monitoring', 'SIEM', 'audit log', 'log retention', 'alerting', 'detection'],
    short_answer: 'All access and security events are logged centrally. Logs are retained for 12 months. A SIEM with real-time alerting monitors for anomalies and threats.',
    tags: ['monitoring', 'logging', 'detection'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-04-15',
    evidence_ids: ['ev-004'],
    long_answer_md: `## Logging and Monitoring\n\n### What We Log\n- Authentication events (success and failure)\n- Privileged access and admin actions\n- API calls (with user/IP context)\n- Infrastructure changes (CloudTrail)\n- Application errors and exceptions\n\n### Retention\nLogs are retained for 12 months in immutable storage.\n\n### Alerting\nReal-time alerts for: brute-force attempts, impossible travel, privilege escalation, data exfiltration patterns.`,
  },
  {
    id: 'ans-014',
    title: 'Data Classification',
    intent_keywords: ['data classification', 'data sensitivity', 'confidential', 'PII', 'sensitive data', 'labelling'],
    short_answer: 'We classify data into four tiers: Public, Internal, Confidential, and Restricted. Handling procedures and controls are defined per tier.',
    tags: ['data-classification', 'governance', 'privacy'],
    frameworks: ['ISO27001', 'SOC2', 'SIG'],
    owner: 'privacy@cloudwidget.example',
    last_reviewed: '2025-02-01',
    evidence_ids: ['ev-009'],
    long_answer_md: `## Data Classification\n\n| Tier | Examples | Controls |\n|------|----------|----------|\n| Public | Marketing content | No restrictions |\n| Internal | Employee handbook | Authentication required |\n| Confidential | Customer data | Encryption + access controls + logging |\n| Restricted | Financial data, credentials | Encryption + strict RBAC + audit + DLP |`,
  },
  {
    id: 'ans-015',
    title: 'Physical Security',
    intent_keywords: ['physical security', 'data center', 'facility', 'badge access', 'visitor', 'CCTV'],
    short_answer: 'We operate in SOC 2 Type II certified data centers (AWS). Physical access controls include badge-only entry, CCTV, and visitor logging. No customer systems are hosted on-premises.',
    tags: ['physical-security', 'infrastructure', 'facilities'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'infrastructure@cloudwidget.example',
    last_reviewed: '2025-01-15',
    evidence_ids: ['ev-001'],
    long_answer_md: `## Physical Security\n\nOur production infrastructure runs entirely on Amazon Web Services (AWS). Physical security controls for AWS data centers include:\n\n- Perimeter security with 24/7 security staff\n- Multi-layer access control (badge + biometric)\n- CCTV coverage and tamper monitoring\n- ISO 27001 and SOC 2 certified facilities\n\nWe do not operate on-premises servers. AWS physical security documentation is available at: https://aws.amazon.com/compliance/data-center/`,
  },
  {
    id: 'ans-016',
    title: 'Change Management',
    intent_keywords: ['change management', 'change control', 'release process', 'deployment', 'SDLC', 'code review'],
    short_answer: 'All changes go through a documented change management process including peer code review, automated testing, and staged deployment before production release.',
    tags: ['change-management', 'sdlc', 'operations'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'engineering@cloudwidget.example',
    last_reviewed: '2025-03-01',
    evidence_ids: ['ev-006'],
    long_answer_md: `## Change Management\n\n### Process\n1. Feature branch with peer code review (2+ approvers required)\n2. Automated CI: unit tests, SAST, dependency scan\n3. Deploy to staging with automated smoke tests\n4. Change ticket approved by engineering lead\n5. Production deploy with automated rollback trigger\n\n### Emergency Changes\nEmergency hotfixes follow a streamlined path with post-deployment review within 24 hours.`,
  },
  {
    id: 'ans-017',
    title: 'Cryptographic Key Management',
    intent_keywords: ['key management', 'KMS', 'cryptographic keys', 'key rotation', 'HSM', 'secrets management'],
    short_answer: 'Cryptographic keys are managed via AWS KMS with automatic annual rotation. Application secrets are stored in AWS Secrets Manager with access auditing.',
    tags: ['encryption', 'key-management', 'infrastructure'],
    frameworks: ['SOC2', 'ISO27001', 'SIG'],
    owner: 'security@cloudwidget.example',
    last_reviewed: '2025-04-01',
    evidence_ids: ['ev-001', 'ev-002'],
    long_answer_md: `## Cryptographic Key Management\n\n- **AWS KMS** for data encryption keys (DEKs) and key encryption keys (KEKs)\n- **Automatic rotation**: KMS keys rotate annually\n- **AWS Secrets Manager**: Application secrets (DB passwords, API keys)\n- **No hardcoded secrets**: Enforced via pre-commit hooks and SAST\n- **Key access**: Logged in CloudTrail; alerts on unusual access patterns`,
  },
  {
    id: 'ans-018',
    title: 'Network Security',
    intent_keywords: ['network security', 'firewall', 'VPC', 'WAF', 'DDoS', 'network segmentation', 'zero trust'],
    short_answer: 'Production infrastructure is deployed in a private VPC with strict security group rules. A WAF filters malicious traffic; DDoS protection is provided by AWS Shield.',
    tags: ['network-security', 'infrastructure', 'perimeter'],
    frameworks: ['SOC2', 'ISO27001', 'SIG', 'CAIQ'],
    owner: 'infrastructure@cloudwidget.example',
    last_reviewed: '2025-04-15',
    evidence_ids: ['ev-002'],
    long_answer_md: `## Network Security\n\n### Perimeter\n- AWS WAF on all internet-facing endpoints\n- AWS Shield Standard for DDoS protection (Shield Advanced for Enterprise)\n- CloudFront CDN with geographic access controls\n\n### Internal\n- VPC with private subnets for all backend services\n- Security groups follow least-privilege (deny by default)\n- VPC Flow Logs enabled for all network interfaces\n- No SSH access to production; bastion-less via AWS SSM Session Manager`,
  },
  {
    id: 'ans-019',
    title: 'GDPR / Privacy Compliance',
    intent_keywords: ['GDPR', 'privacy', 'data subject', 'DPA', 'privacy policy', 'lawful basis', 'consent'],
    short_answer: 'We are GDPR compliant as a data processor. We sign DPAs with all customers. A DPO is appointed; subject rights requests are handled within statutory timelines.',
    tags: ['gdpr', 'privacy', 'compliance', 'legal'],
    frameworks: ['CAIQ', 'ISO27001', 'SIG'],
    owner: 'privacy@cloudwidget.example',
    last_reviewed: '2025-02-15',
    evidence_ids: ['ev-009', 'ev-010'],
    long_answer_md: `## GDPR / Privacy Compliance\n\n- We act as a **data processor** for customer data; customers are controllers\n- **DPA**: Available for signing via our privacy portal\n- **DPO**: Appointed; contact dpo@cloudwidget.example\n- **Lawful basis**: Processing under contract performance and legitimate interest\n- **Data subject rights**: Access, rectification, erasure, portability handled within 30 days\n- **Cross-border transfers**: EU-US Data Privacy Framework + SCCs for non-EU countries`,
  },
  {
    id: 'ans-020',
    title: 'Security Certifications and Audits',
    intent_keywords: ['SOC 2', 'ISO 27001', 'certification', 'audit', 'compliance', 'attestation', 'assurance'],
    short_answer: 'We hold SOC 2 Type II (Trust Services Criteria: Security, Availability, Confidentiality). ISO 27001 certification is in progress. Reports available under NDA.',
    tags: ['certifications', 'compliance', 'assurance'],
    frameworks: ['SOC2', 'ISO27001', 'SIG', 'CAIQ'],
    owner: 'compliance@cloudwidget.example',
    last_reviewed: '2025-01-01',
    evidence_ids: ['ev-001', 'ev-010'],
    long_answer_md: `## Security Certifications\n\n| Certification | Status | Scope |\n|--------------|--------|-------|\n| SOC 2 Type II | ✅ Current | Security, Availability, Confidentiality |\n| ISO 27001 | 🔄 In Progress | Full ISMS |\n| CSA STAR | ✅ Level 1 Self-Assessment | Cloud security |\n| PCI-DSS | ❌ Not Applicable | We do not process payment cards |\n\nSOC 2 reports are available under NDA. Request at: compliance@cloudwidget.example`,
  },
];

export const DEMO_EVIDENCE: Evidence[] = [
  {
    id: 'ev-001',
    title: 'SOC 2 Type II Report (2024)',
    type: 'doc',
    url_or_path: 'https://trust.cloudwidget.example/soc2-2024',
    description: 'Annual SOC 2 Type II audit report covering Security, Availability, and Confidentiality Trust Services Criteria. Available under NDA.',
    last_updated: '2025-01-15',
    tags: ['audit', 'SOC2', 'compliance', 'assurance'],
  },
  {
    id: 'ev-002',
    title: 'Encryption Architecture Document',
    type: 'doc',
    url_or_path: 'evidence/files/encryption-architecture.pdf',
    description: 'Internal document describing encryption implementation: AES-256-GCM at rest, TLS 1.2+ in transit, KMS key hierarchy, and rotation schedule.',
    last_updated: '2025-03-01',
    tags: ['encryption', 'architecture', 'technical'],
  },
  {
    id: 'ev-003',
    title: 'Access Control Policy',
    type: 'doc',
    url_or_path: 'evidence/files/access-control-policy.pdf',
    description: 'Formal policy document covering RBAC framework, MFA requirements, access reviews, and privileged access management procedures.',
    last_updated: '2025-02-01',
    tags: ['access-control', 'policy', 'MFA', 'RBAC'],
  },
  {
    id: 'ev-004',
    title: 'Incident Response Plan',
    type: 'doc',
    url_or_path: 'evidence/files/incident-response-plan.pdf',
    description: 'Documented Incident Response Plan following NIST SP 800-61. Includes CSIRT charter, runbooks, escalation matrix, and communication templates.',
    last_updated: '2025-01-10',
    tags: ['incident-response', 'policy', 'operations'],
  },
  {
    id: 'ev-005',
    title: 'Penetration Test Report Summary (2024)',
    type: 'doc',
    url_or_path: 'evidence/files/pentest-summary-2024.pdf',
    description: 'Executive summary from annual penetration test conducted by SecureStrike LLC. All High/Critical findings remediated. Full report available under NDA.',
    last_updated: '2024-11-30',
    tags: ['penetration-test', 'assessment', 'security-testing'],
  },
  {
    id: 'ev-006',
    title: 'SDLC and Change Management Policy',
    type: 'doc',
    url_or_path: 'evidence/files/sdlc-policy.pdf',
    description: 'Software Development Lifecycle and Change Management policy covering code review requirements, CI/CD security gates, and deployment approvals.',
    last_updated: '2025-03-01',
    tags: ['sdlc', 'change-management', 'policy'],
  },
  {
    id: 'ev-007',
    title: 'Business Continuity and DR Plan',
    type: 'doc',
    url_or_path: 'evidence/files/bcp-dr-plan.pdf',
    description: 'Business Continuity and Disaster Recovery Plan including RTO/RPO commitments, multi-region architecture diagram, and last tabletop exercise results.',
    last_updated: '2025-01-10',
    tags: ['bcp', 'disaster-recovery', 'resilience'],
  },
  {
    id: 'ev-008',
    title: 'Security Training Completion Report',
    type: 'doc',
    url_or_path: 'evidence/files/training-completion-2024.pdf',
    description: 'Annual security awareness training completion report showing 100% employee completion for FY2024. Includes phishing simulation metrics.',
    last_updated: '2025-01-31',
    tags: ['training', 'awareness', 'compliance'],
  },
  {
    id: 'ev-009',
    title: 'Privacy Policy and DPA Template',
    type: 'link',
    url_or_path: 'https://cloudwidget.example/legal/privacy',
    description: 'Public privacy policy and Data Processing Agreement template for GDPR compliance. DPA covers lawful basis, sub-processors, international transfers, and subject rights.',
    last_updated: '2025-02-15',
    tags: ['privacy', 'gdpr', 'legal', 'DPA'],
  },
  {
    id: 'ev-010',
    title: 'CSA STAR Self-Assessment',
    type: 'link',
    url_or_path: 'https://cloudsecurityalliance.org/star/registry/cloudwidget',
    description: 'Cloud Security Alliance (CSA) STAR Level 1 Self-Assessment available publicly on the CSA registry. Covers CAIQ v4 controls.',
    last_updated: '2025-01-01',
    tags: ['CSA', 'STAR', 'CAIQ', 'cloud-security'],
  },
];

export const DEMO_QUESTIONNAIRE: Questionnaire = {
  slug: 'demo-sig-lite',
  source_filename: 'SIG-Lite-Demo.csv',
  imported_at: '2025-06-01T00:00:00.000Z',
  questions: [
    { qid: 'A.1', section: 'Access Control', text: 'Does your organization implement role-based access control (RBAC)?', answer_type: 'yes_no' },
    { qid: 'A.2', section: 'Access Control', text: 'Is multi-factor authentication (MFA) required for all privileged accounts?', answer_type: 'yes_no' },
    { qid: 'A.3', section: 'Access Control', text: 'Do you perform periodic access reviews to validate user access rights?', answer_type: 'yes_no' },
    { qid: 'A.4', section: 'Access Control', text: 'Describe your process for revoking access when an employee leaves the organization.', answer_type: 'text' },
    { qid: 'B.1', section: 'Cryptography', text: 'Is data at rest encrypted? If yes, describe the algorithm and key length used.', answer_type: 'text' },
    { qid: 'B.2', section: 'Cryptography', text: 'Is data in transit encrypted using TLS 1.2 or higher?', answer_type: 'yes_no' },
    { qid: 'B.3', section: 'Cryptography', text: 'Do you have a formal key management policy covering key generation, rotation, and destruction?', answer_type: 'yes_no' },
    { qid: 'C.1', section: 'Incident Management', text: 'Do you have a documented Incident Response Plan (IRP)?', answer_type: 'yes_no' },
    { qid: 'C.2', section: 'Incident Management', text: 'How quickly do you notify customers of a confirmed data breach?', answer_type: 'text' },
    { qid: 'C.3', section: 'Incident Management', text: 'Is your IRP tested at least annually?', answer_type: 'yes_no' },
    { qid: 'D.1', section: 'Vulnerability Management', text: 'Do you conduct regular vulnerability scanning of your systems?', answer_type: 'yes_no' },
    { qid: 'D.2', section: 'Vulnerability Management', text: 'Do you perform penetration testing at least annually?', answer_type: 'yes_no' },
    { qid: 'D.3', section: 'Vulnerability Management', text: 'What is your SLA for patching Critical and High severity vulnerabilities?', answer_type: 'text' },
    { qid: 'E.1', section: 'Data Management', text: 'Do you have a data classification policy?', answer_type: 'yes_no' },
    { qid: 'E.2', section: 'Data Management', text: 'Describe your data retention and deletion policies.', answer_type: 'text' },
    { qid: 'E.3', section: 'Data Management', text: 'Are customer data backups encrypted and stored separately from primary data?', answer_type: 'yes_no' },
    { qid: 'F.1', section: 'Operational Security', text: 'Do you log and monitor access to systems containing customer data?', answer_type: 'yes_no' },
    { qid: 'F.2', section: 'Operational Security', text: 'Do you have a formal change management process?', answer_type: 'yes_no' },
    { qid: 'G.1', section: 'Human Resources Security', text: 'Do employees receive security awareness training?', answer_type: 'yes_no' },
    { qid: 'G.2', section: 'Human Resources Security', text: 'Are background checks performed on employees with access to sensitive systems?', answer_type: 'yes_no_na' },
    { qid: 'H.1', section: 'Physical Security', text: 'Are your data centers certified to ISO 27001 or SOC 2?', answer_type: 'yes_no' },
    { qid: 'H.2', section: 'Physical Security', text: 'Is physical access to servers restricted to authorised personnel only?', answer_type: 'yes_no' },
    { qid: 'I.1', section: 'Compliance', text: 'Does your organization hold a current SOC 2 Type II report?', answer_type: 'yes_no' },
    { qid: 'I.2', section: 'Compliance', text: 'Is your organization certified to ISO 27001?', answer_type: 'yes_no_na' },
    { qid: 'I.3', section: 'Compliance', text: 'Are you GDPR compliant for handling EU personal data?', answer_type: 'yes_no' },
    { qid: 'J.1', section: 'Third-Party Risk', text: 'Do you conduct security assessments of your critical sub-processors and vendors?', answer_type: 'yes_no' },
    { qid: 'J.2', section: 'Third-Party Risk', text: 'Do you maintain a list of sub-processors accessible to customers?', answer_type: 'yes_no' },
    { qid: 'K.1', section: 'Business Continuity', text: 'Do you have a Business Continuity Plan (BCP)?', answer_type: 'yes_no' },
    { qid: 'K.2', section: 'Business Continuity', text: 'What are your RTO and RPO commitments?', answer_type: 'text' },
    { qid: 'K.3', section: 'Business Continuity', text: 'Is your BCP tested at least annually?', answer_type: 'yes_no' },
  ],
};

export const DEMO_MAPPING: Mapping = {
  'A.1': { answer_id: 'ans-004' },
  'A.2': { answer_id: 'ans-003' },
  'A.3': { answer_id: 'ans-004', override_text: 'Access reviews are conducted quarterly. Results are documented and reviewed by the Security team.' },
  'A.4': { answer_id: 'ans-004', override_text: 'Upon employee departure, IT revokes all access within 4 hours of HR notification. Accounts are disabled, MFA revoked, and shared credentials rotated.' },
  'B.1': { answer_id: 'ans-001' },
  'B.2': { answer_id: 'ans-002' },
  'B.3': { answer_id: 'ans-017' },
  'C.1': { answer_id: 'ans-005' },
  'C.2': { answer_id: 'ans-005', override_text: 'Customers are notified within 72 hours of a confirmed breach, per GDPR Article 33 requirements. We provide incident updates until closure.' },
  'C.3': { answer_id: 'ans-005' },
  'D.1': { answer_id: 'ans-006' },
  'D.2': { answer_id: 'ans-012' },
  'D.3': { answer_id: 'ans-006', override_text: 'Critical: 24 hours. High: 7 days. Medium: 30 days. Low: 90 days. SLAs are tracked in our vulnerability management platform.' },
  'E.1': { answer_id: 'ans-014' },
  'E.2': { answer_id: 'ans-010' },
  'E.3': { answer_id: 'ans-007' },
  'F.1': { answer_id: 'ans-013' },
  'F.2': { answer_id: 'ans-016' },
  'G.1': { answer_id: 'ans-008' },
  'G.2': { answer_id: 'ans-008', override_text: 'Background checks are conducted for all employees and contractors with access to production systems or customer data, subject to local law.' },
  'H.1': { answer_id: 'ans-015' },
  'H.2': { answer_id: 'ans-015' },
  'I.1': { answer_id: 'ans-020' },
  'I.2': { answer_id: 'ans-020' },
  'I.3': { answer_id: 'ans-019' },
  'J.1': { answer_id: 'ans-009' },
  'J.2': { answer_id: 'ans-009' },
  'K.1': { answer_id: 'ans-011' },
  'K.2': { answer_id: 'ans-007', override_text: 'RTO: 4 hours. RPO: 1 hour. Commitments are documented in our MSA/SLA. Enterprise customers can negotiate tighter commitments.' },
  'K.3': { answer_id: 'ans-011' },
};
